language: c
dist: trusty
sudo: false
group: beta

git:
    depth: 10

branches:
    only:
        - 2.7

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - TESTING=cpython

matrix:
  fast_finish: true
  include:
    - os: linux
      language: cpp
      compiler: clang
      env:
        - TESTING="C++ header compatibility"
      before_script:
        - ./configure
      script:
        - echo '#include "Python.h"' > test.cc && $CXX -c test.cc -o /dev/null -I ./Include -I .
  exclude:
    - os: osx
      compiler: gcc

# Travis provides only 2 cores, so don't overdo the parallelism and waste memory.
before_script:
  - |
      ./configure --with-pydebug
      make -j4

script:
  # `-r -w` implicitly provided through `make buildbottest`.
  - make buildbottest TESTOPTS="-j4"
